version: '3.7'
services:
  database:
    image: mariadb
    restart: always
    ports:
      - '6000:3306'
  web:
    image: bulletin-board
    depends_on:
      - database
    environment:
      WAIT_HOSTS: database:3306
    ports:
      - '3000:3000'
