# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#  
version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      # Update npm to the latest
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # Install dependencies
      - run:
          name: Install npm wee
          command: npm install
      - persist_to_workspace:
          root: ~/repo
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ls -a
      - run: npm test

workflows:
  version: 2

  btd:
    jobs:
      - build
      - test:
          requires:
            - build