# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      # Update npm to the latest
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # Install dependencies
      - run:
          name: Install npm wee
          command: npm install
      - persist_to_workspace:
          root: ~/repo
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm test

  compile:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run tsc

  deploy:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker
      - run:
          name: Build the image
          command: docker build -t romppane/bulletin-board:$CIRCLE_SHA1 .
      - run:
          name: Login to Docker
          command: docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
      - run:
          name: Push to DockerHub
          command: docker push romppane/bulletin-board:$CIRCLE_SHA1
      - run:
          name: Login to registery
          command: docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Deploy to Heroku
          command: docker tag romppane/bulletin-board:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
      - run:
          name: Release on Heroku
          command: docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  btd:
    jobs:
      - build
      - test:
          requires:
            - build
      - compile:
          requires:
            - test
      - deploy:
          requires:
            - compile
