# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
executors:
  my-executor:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      # Update npm to the latest
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      # Install dependencies
      - run:
          name: Install npm wee
          command: npm install
      - persist_to_workspace:
          root: ~/repo
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm test

  compile:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm run tsc

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  btd:
    jobs:
      - build
      - test:
          requires:
            - build
      - compile:
          requires:
            - build
            - test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
            - test
            - compile
