export class User {

  // Not putting too many variables here yet, as I've still to study log in possiblities. How does Google sign in for example work?
  private id: number;
  private avatar: string;

  public constructor(id: number, avatar: string){
    // Will be autogenerated
    this.id = id;
    this.avatar = avatar;
  }

  public getId() : number {
    return this.id;
  }

  public setAvatar(avatar : string) {
    this.avatar = avatar;
  }

  public getAvatar() : string {
    return this.avatar;
  }
}
